In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame({'Experience':[1,2,3,4,5,3,4,1],
                   'Salary':[30,35,42,45,50,40,43,32]})
df

,Experience,Salary
0,1,30
1,2,35
2,3,42
3,4,45
4,5,50
5,3,40
6,4,43
7,1,32


In [ ]:
X = df[['Experience']]
y = df['Salary']

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

In [ ]:
model.fit(X,y)

LinearRegression()

In [ ]:
model.coef_

array([4.61344538])

In [ ]:
model.intercept_

np.float64(26.36134453781513)

In [ ]:
new_datapoint = pd.DataFrame({'Experience':[6]})
new_datapoint

,Experience
0,6


In [ ]:
y_pred = model.predict(new_datapoint)
y_pred

array([54.04201681])

In [ ]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,train_size = 0.80)

In [ ]:
X_train

,Experience
4,5
1,2
2,3
6,4
5,3
7,1


In [ ]:
X_test

,Experience
3,4
0,1


In [ ]:
y_train

,Salary
4,50
1,35
2,42
6,43
5,40
7,32


In [ ]:
y_test

,Salary
3,45
0,30


In [ ]:
y_predict = model.predict(X_test)

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, root_mean_squared_error

In [ ]:
mean_absolute_error(y_test,y_predict)

0.5798319327731107

In [ ]:
mean_squared_error(y_test,y_predict)

0.49219687875150403

In [ ]:
root_mean_squared_error(y_test,y_predict)

0.7015674441930042

## Dataset2

In [ ]:
df = pd.read_csv('/content/linear regression dataset.csv')

In [ ]:
df

,x,y
0,24.0,21.549452
1,50.0,47.464463
2,15.0,17.218656
3,38.0,36.586398
4,87.0,87.288984
...,...,...
695,58.0,58.595006
696,93.0,94.625094
697,82.0,88.603770
698,66.0,63.648685


In [ ]:
df = df.dropna()
df.isnull().sum()

,0
x,0
y,0


In [ ]:
df.shape

(699, 2)

In [ ]:
X = df[['x']]
y = df['y']

In [ ]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,train_size = 0.80,random_state=42)

In [ ]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [ ]:
model.coef_

array([1.00121676])

In [ ]:
model.intercept_

np.float64(-0.09664630862199175)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
X_test.shape

(140, 1)

In [ ]:
y_pred

array([ 1.00025030e+02,  9.70213794e+01,  1.19179548e+01,  8.60079950e+01,
        9.10140788e+01,  1.00025030e+02,  6.49824431e+01,  2.49337727e+01,
        3.39447235e+01,  2.19301224e+01,  6.09775760e+01,  2.19301224e+01,
        5.09654084e+01,  4.90943749e+00,  1.90578721e+00,  3.19422900e+01,
        2.49337727e+01, -9.66463086e-02,  3.49459403e+01,  4.29556744e+01,
        9.90238129e+01,  1.69240386e+01,  2.39325559e+01,  9.04570451e-01,
        4.90943749e+00,  7.39933939e+01,  2.89386397e+01,  1.39203883e+01,
        3.49459403e+01,  7.79982610e+01,  6.79860934e+01,  1.39203883e+01,
        7.89994777e+01,  5.59714922e+01,  5.19666252e+01,  7.59958274e+01,
        4.29556744e+01,  2.29313392e+01,  9.10140788e+01,  2.69362062e+01,
        1.90578721e+00,  4.90943749e+00,  4.99641917e+01,  4.39568911e+01,
        4.69605414e+01,  2.90700397e+00,  5.79739258e+01,  9.80225962e+01,
        6.91187101e+00,  6.91187101e+00,  3.69483738e+01,  5.29678420e+01,
        3.39447235e+01,  

In [ ]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_pred)

2.2020818674091127

In [ ]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred)

7.752986666319193

In [ ]:
from sklearn.metrics import root_mean_squared_error
root_mean_squared_error(y_test, y_pred)

2.7844185508502837

**Assumptions for Linear Regression**

<br>

| Assumption | Description | How to Check | Consequence if Violated |
|---|---|---|---|
| **Linearity** | Relationship between X and Y is linear | Scatterplot, Residuals vs Fitted plot | Biased/incorrect predictions |
| **Independence of Errors** | Residuals are not correlated with each other | Durbin-Watson test, know data collection process | Unreliable p-values (false significance) |
| **Homoscedasticity** | Constant variance of residuals across all X | Residuals vs Fitted plot (look for funnel shape) | Incorrect standard errors, unreliable p-values |
| **Normality of Residuals** | Residuals are approximately normally distributed | Q-Q plot, Histogram, Shapiro-Wilk test | Unreliable confidence intervals (mainly small samples) |
| **No Multicollinearity** | Independent variables aren't highly correlated with each other | VIF (Variance Inflation Factor), Correlation matrix | Unstable, hard-to-interpret coefficients |

<br><br>
**Additional Assumption Point**
<br>

| Assumption | Description | How to Check | Consequence if Violated |
|---|---|---|---|
| **No Significant Outliers** | No extreme points disproportionately influencing the fit | Cook's Distance, Leverage plots | Model skewed by a few points |
| **No Measurement Error in X** | Predictors are measured accurately | Domain knowledge, data collection review | Biased coefficient estimates |